/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Swing;

import Domain.Sales.Product;
import TechnicalServices.Persistence.PersistentStorage;
import TechnicalServices.Persistence.TransferFromDB;
import com.mysql.cj.protocol.Resultset;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.SwingWorker;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Alaa Shafshak
 */
public class NewSaleFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewSaleFrame
     */
    
    private final GuiListModels<String> productModel = new GuiListModels();
    private final GuiListModels<String> chosenModel = new GuiListModels();
    PaymentMethodFrame paymentmethod;
    QuantityFrame qf; 
    Product p;
    List <String> ls;
    
    public NewSaleFrame() throws SQLException {
        initComponents();
        //getting the catalog from the db to set in the the products list 
        ResultSet set = (ResultSet) TransferFromDB.instance.getCatalog();
        while(set.next()){
            String name = set.getString(3);
            productModel.add(name);     
        }
        initActions();
    }

    private void initActions() {
        setLocation(100, 70);
        
        productsList.setModel(productModel);
        saleList.setModel(chosenModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        saleList = new javax.swing.JList<>();
        endSaleBtn = new javax.swing.JButton();
        cancelBtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Products");

        productsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productsList);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Sale Products");

        jScrollPane2.setViewportView(saleList);

        endSaleBtn.setText("End Sale");
        endSaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endSaleBtnActionPerformed(evt);
            }
        });

        cancelBtn2.setText("Cancel");
        cancelBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(cancelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(endSaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel1)
                                .addGap(144, 144, 144))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endSaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //when clicking twice on a product from the productsList, a quantity frame will be displayed to set the quantity of the chosen product and then it will be added to the second list(chosenList)
    private void productsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsListMouseClicked

        if (evt.getClickCount() == 2) {
            if (productModel.isEmpty()) {
                return;
            }
             
            String selectedname = productsList.getSelectedValue();
            if (!chosenModel.contains(selectedname)) {
                chosenModel.add(selectedname);
                saleList.ensureIndexIsVisible(chosenModel.getSize() - 1);
            }
           
            try {
                qf = new QuantityFrame();
            } catch (SQLException ex) {
                Logger.getLogger(NewSaleFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            qf.setVisible(true);
        }
    }//GEN-LAST:event_productsListMouseClicked
    //when the end sale button is clicked, the paymentmethod frame will be displayed to calculate the total and choose the payment method
    private void endSaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endSaleBtnActionPerformed
        
        ls = chosenModel.getAll();
        
        try {
            paymentmethod = new PaymentMethodFrame(ls,qf.value);
        } catch (SQLException ex) {
            Logger.getLogger(NewSaleFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (paymentmethod.isVisible()) { 
            paymentmethod.setEnabled(true);
            return;
        }
        paymentmethod.setVisible(true);
        new addNewSaleList().execute();
    }//GEN-LAST:event_endSaleBtnActionPerformed

    private void cancelBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn2ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_cancelBtn2ActionPerformed

     private class addNewSaleList extends SwingWorker<Void, Void> {

        public addNewSaleList() {
         
        }

        @Override
        protected Void doInBackground() throws Exception {
            PersistentStorage.instance.makeNewSale();
            return null;
        }
    

        @Override
        public void done() {
           // JOptionPane.showMessageDialog(rootPane, "New Sale Added Successfully!");
        }
 
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn2;
    private javax.swing.JButton endSaleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> productsList;
    private javax.swing.JList<String> saleList;
    // End of variables declaration//GEN-END:variables
}
